### ISSUE TITLE
RegexChecker splits on spaces

### ISSUE THREAD

**Issue by ScoreUnder** [Brod8362/discord-bot-2#1]
The two major uses for the regex checker at the moment are for English and Japanese messages.

The regex checker currently splits on spaces, which has a few important consequences:

* There is no possible way to match on multi-word phrases.
* Japanese text is difficult to match on because is has no word boundaries.
* Words in English still need to be matched like `.*\btest\b.*` (arguably worse than when it was using an unanchored regex on the whole string), because the text may be surrounded by punctuation on either side, e.g. "(test)", or may be part of a hyphenated compound, e.g. "test-style".

Also, it would be ideal to have the `RegexChecker` check case-insensitively.

So here the tasks are roughly:
- [x] Rewrite `RegexChecker` to work without splitting the message
- [x] Use case-insensitive regexes by default

Bonus:
- [x] Change existing regexes in the DB to be compatible (probably just a matter of adding `\b` either side if it doesn't already exist and replacing all `.` with `\S` (note capital S), if it's not escaped already)
- [x] Strip `(?i)` from existing regexes once case insensitivity is default
- [x] Cache compiled patterns instead of regex strings (and if the original string is needed, there is a way to get the original regex "source code" string from a Pattern object, using the [`Pattern#pattern()`][1] method)

[1]: https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/util/regex/Pattern.html#pattern()

**Comment by ScoreUnder** [comment]
![](https://i.imgur.com/FdniS4V.png)

**Comment by Brod8362** [comment]
Fixed for v1.3.
